# Generated by Django 4.0.3 on 2022-04-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newton',
            name='body',
        ),
    ]
